// <auto-generated />
namespace EF.Mssql.CodeFirst.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class addNewProperty : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addNewProperty));
        
        string IMigrationMetadata.Id
        {
            get { return "202008191513361_addNewProperty"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
