// <auto-generated />
namespace EF.Mssql.CodeFirst.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class addTeacher : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addTeacher));
        
        string IMigrationMetadata.Id
        {
            get { return "202008191522301_addTeacher"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
